import type { ErStatus } from '@/mockData/aedAndEmergency';

/** 응급실 mock — API 미연동·검색 데모용 */
export type MockEmergencyHospital = {
  hpid: string;
  hospitalName: string;
  department: string;
  address: string;
  latitude: number;
  longitude: number;
  totalBeds: number;
  availableBeds: number;
  availablePediatricErBeds: number;
  status: ErStatus;
  waitMin: number;
  specialties: string[];
  phone: string;
  isPediatricPriority: boolean;
  onCallDoctor?: string;
};

export const MOCK_EMERGENCY_HOSPITALS: MockEmergencyHospital[] = [
  {
    hpid: 'mock-er-snuh',
    hospitalName: '서울대학교병원',
    department: '응급의학과',
    address: '서울특별시 종로구 대학로 101',
    latitude: 37.5799,
    longitude: 126.9968,
    totalBeds: 38,
    availableBeds: 3,
    availablePediatricErBeds: 1,
    status: 'congested',
    waitMin: 75,
    specialties: ['외상', '뇌졸중', '심장', '소아'],
    phone: '02-2072-2475',
    isPediatricPriority: true,
    onCallDoctor: '응급의학과 당직',
  },
  {
    hpid: 'mock-er-severance',
    hospitalName: '신촌세브란스병원',
    department: '응급의학과',
    address: '서울특별시 서대문구 연세로 50-1',
    latitude: 37.5622,
    longitude: 126.9407,
    totalBeds: 42,
    availableBeds: 9,
    availablePediatricErBeds: 3,
    status: 'available',
    waitMin: 28,
    specialties: ['외상', '심장', '소아', '화상'],
    phone: '02-2228-5800',
    isPediatricPriority: true,
  },
  {
    hpid: 'mock-er-asan',
    hospitalName: '서울아산병원',
    department: '응급의학과',
    address: '서울특별시 송파구 올림픽로43길 88',
    latitude: 37.5269,
    longitude: 127.1086,
    totalBeds: 45,
    availableBeds: 7,
    availablePediatricErBeds: 2,
    status: 'available',
    waitMin: 32,
    specialties: ['외상', '심장', '장기이식', '소아'],
    phone: '02-3010-3114',
    isPediatricPriority: true,
  },
  {
    hpid: 'mock-er-samsung',
    hospitalName: '삼성서울병원',
    department: '응급의학과',
    address: '서울특별시 강남구 일원로 81',
    latitude: 37.4881,
    longitude: 127.0856,
    totalBeds: 40,
    availableBeds: 5,
    availablePediatricErBeds: 2,
    status: 'congested',
    waitMin: 48,
    specialties: ['외상', '뇌졸중', '심장'],
    phone: '02-3410-0200',
    isPediatricPriority: true,
  },
  {
    hpid: 'mock-er-korea',
    hospitalName: '고려대학교병원',
    department: '응급의학과',
    address: '서울특별시 성북구 고려대로 73',
    latitude: 37.5874,
    longitude: 127.0268,
    totalBeds: 32,
    availableBeds: 6,
    availablePediatricErBeds: 1,
    status: 'available',
    waitMin: 35,
    specialties: ['외상', '중독', '심장'],
    phone: '02-920-5114',
    isPediatricPriority: false,
  },
  {
    hpid: 'mock-er-cmc',
    hospitalName: '가톨릭대학교 서울성모병원',
    department: '응급의학과',
    address: '서울특별시 서초구 반포대로 222',
    latitude: 37.5016,
    longitude: 127.0048,
    totalBeds: 36,
    availableBeds: 4,
    availablePediatricErBeds: 2,
    status: 'congested',
    waitMin: 52,
    specialties: ['외상', '소아', '화상'],
    phone: '02-2258-6114',
    isPediatricPriority: true,
  },
  {
    hpid: 'mock-er-ajou',
    hospitalName: '아주대병원',
    department: '응급의학과',
    address: '경기도 수원시 영통구 월드컵로 164',
    latitude: 37.4198,
    longitude: 127.1265,
    totalBeds: 34,
    availableBeds: 8,
    availablePediatricErBeds: 2,
    status: 'available',
    waitMin: 30,
    specialties: ['외상', '심장', '소아'],
    phone: '031-219-5114',
    isPediatricPriority: true,
  },
  {
    hpid: 'mock-er-snuh-bundang',
    hospitalName: '분당서울대병원',
    department: '응급의학과',
    address: '경기도 성남시 분당구 구미로 173',
    latitude: 37.3521,
    longitude: 127.1235,
    totalBeds: 37,
    availableBeds: 6,
    availablePediatricErBeds: 3,
    status: 'available',
    waitMin: 38,
    specialties: ['외상', '뇌졸중', '소아', '달빛어린이'],
    phone: '031-787-7114',
    isPediatricPriority: true,
  },
  {
    hpid: 'mock-er-nmc',
    hospitalName: '국립중앙의료원',
    department: '응급의학과',
    address: '서울특별시 중구 을지로 245',
    latitude: 37.5663,
    longitude: 127.0045,
    totalBeds: 35,
    availableBeds: 2,
    availablePediatricErBeds: 0,
    status: 'congested',
    waitMin: 55,
    specialties: ['외상', '화상', '중독'],
    phone: '02-2260-7114',
    isPediatricPriority: false,
  },
  {
    hpid: 'mock-er-redcross',
    hospitalName: '서울적십자병원',
    department: '응급의학과',
    address: '서울특별시 중구 소공로 79',
    latitude: 37.5645,
    longitude: 126.9778,
    totalBeds: 28,
    availableBeds: 6,
    availablePediatricErBeds: 1,
    status: 'available',
    waitMin: 25,
    specialties: ['외상', '심장', '뇌졸중'],
    phone: '02-2002-8000',
    isPediatricPriority: false,
  },
  {
    hpid: 'mock-er-kyunghee',
    hospitalName: '경희대학교병원',
    department: '응급의학과',
    address: '서울특별시 동대문구 경희대로 23',
    latitude: 37.5941,
    longitude: 127.0476,
    totalBeds: 30,
    availableBeds: 4,
    availablePediatricErBeds: 1,
    status: 'available',
    waitMin: 35,
    specialties: ['외상', '한방응급', '중독'],
    phone: '02-958-8114',
    isPediatricPriority: false,
  },
  {
    hpid: 'mock-er-gangnam-severance',
    hospitalName: '강남세브란스병원',
    department: '응급의학과',
    address: '서울특별시 강남구 언주로 211',
    latitude: 37.5193,
    longitude: 127.0473,
    totalBeds: 33,
    availableBeds: 5,
    availablePediatricErBeds: 2,
    status: 'congested',
    waitMin: 45,
    specialties: ['외상', '심장', '소아'],
    phone: '02-2019-3114',
    isPediatricPriority: true,
  },
  {
    hpid: 'mock-er-hanyang',
    hospitalName: '한양대학교병원',
    department: '응급의학과',
    address: '서울특별시 성동구 왕십리로 222-1',
    latitude: 37.5593,
    longitude: 127.0445,
    totalBeds: 31,
    availableBeds: 7,
    availablePediatricErBeds: 1,
    status: 'available',
    waitMin: 33,
    specialties: ['외상', '심장', '뇌졸중'],
    phone: '02-2290-8114',
    isPediatricPriority: false,
  },
  {
    hpid: 'mock-er-chungang',
    hospitalName: '중앙대학교병원',
    department: '응급의학과',
    address: '서울특별시 동작구 흑석로 102',
    latitude: 37.5066,
    longitude: 126.9608,
    totalBeds: 29,
    availableBeds: 3,
    availablePediatricErBeds: 0,
    status: 'congested',
    waitMin: 50,
    specialties: ['외상', '중독'],
    phone: '02-6299-1114',
    isPediatricPriority: false,
  },
  {
    hpid: 'mock-er-ewha',
    hospitalName: '이대목동병원',
    department: '응급의학과',
    address: '서울특별시 양천구 안양로 1071',
    latitude: 37.5369,
    longitude: 126.8864,
    totalBeds: 32,
    availableBeds: 4,
    availablePediatricErBeds: 2,
    status: 'available',
    waitMin: 36,
    specialties: ['외상', '소아', '산부인과응급'],
    phone: '02-2650-5114',
    isPediatricPriority: true,
  },
  {
    hpid: 'mock-er-konkuk',
    hospitalName: '건국대학교병원',
    department: '응급의학과',
    address: '서울특별시 광진구 능동로 120-1',
    latitude: 37.5404,
    longitude: 127.0719,
    totalBeds: 27,
    availableBeds: 5,
    availablePediatricErBeds: 1,
    status: 'available',
    waitMin: 40,
    specialties: ['외상', '심장'],
    phone: '02-2030-5114',
    isPediatricPriority: false,
  },
  {
    hpid: 'mock-er-sch',
    hospitalName: '순천향대학교 서울병원',
    department: '응급의학과',
    address: '서울특별시 용산구 대사관로 59',
    latitude: 37.5342,
    longitude: 126.9949,
    totalBeds: 26,
    availableBeds: 6,
    availablePediatricErBeds: 0,
    status: 'available',
    waitMin: 29,
    specialties: ['외상', '감염', '중독'],
    phone: '02-709-9114',
    isPediatricPriority: false,
  },
  {
    hpid: 'mock-er-seoul-saengsim',
    hospitalName: '서울성심병원',
    department: '응급의학과',
    address: '서울특별시 동대문구 왕산로 258',
    latitude: 37.5617,
    longitude: 127.0421,
    totalBeds: 24,
    availableBeds: 8,
    availablePediatricErBeds: 1,
    status: 'available',
    waitMin: 22,
    specialties: ['외상', '심장'],
    phone: '02-966-1616',
    isPediatricPriority: false,
  },
  {
    hpid: 'mock-er-inha',
    hospitalName: '인하대병원',
    department: '응급의학과',
    address: '인천광역시 중구 인하로 27',
    latitude: 37.4528,
    longitude: 126.6172,
    totalBeds: 30,
    availableBeds: 5,
    availablePediatricErBeds: 1,
    status: 'available',
    waitMin: 42,
    specialties: ['외상', '해양응급', '화상'],
    phone: '032-890-2114',
    isPediatricPriority: false,
  },
];

export function filterMockEmergencyHospitals(query: string): MockEmergencyHospital[] {
  const q = query.trim().toLowerCase();
  const sorted = [...MOCK_EMERGENCY_HOSPITALS];
  if (!q) return sorted;
  return sorted.filter(
    (item) =>
      item.hospitalName.toLowerCase().includes(q) ||
      item.address.toLowerCase().includes(q) ||
      item.specialties.some((s) => s.toLowerCase().includes(q)),
  );
}

export function findMockEmergencyHospital(hpid: string): MockEmergencyHospital | undefined {
  return MOCK_EMERGENCY_HOSPITALS.find((item) => item.hpid === hpid);
}
