import type { MedicineInfo } from '@/services/emergencyApi';

/** API 키 없을 때 약물정보찾기 화면용 샘플 데이터 (e약은요 형식) */
export const MOCK_MEDICINES: MedicineInfo[] = [
  {
    itemName: '타이레놀정500mg',
    entpName: '한국존슨앤존슨',
    itemSeq: 'mock-tylenol-500',
    itemImage: '',
    efficacy: '해열, 진통(두통, 치통, 생리통, 근육통 등)',
    usage: '성인 및 12세 이상: 1~2정, 1일 3~4회 식후 복용',
    warningBeforeUse: '간질환·알코올 상습 복용자는 의사·약사와 상담하세요.',
    precautions: '1일 최대 용량을 초과하지 마세요. 다른 해열·진통제와 병용 시 주의하세요.',
    interactions: '와파린 등 항응고제와 병용 시 출혈 위험이 증가할 수 있습니다.',
    sideEffects: '드물게 피부 발진, 소화불량, 간 기능 이상이 나타날 수 있습니다.',
    storage: '실온(1~30℃) 보관, 습기와 빛을 피하세요.',
    updatedAt: '20240101',
  },
  {
    itemName: '게보린정',
    entpName: '삼진제약',
    itemSeq: 'mock-geborin',
    itemImage: '',
    efficacy: '두통, 치통, 생리통, 근육통, 감기에 따른 발열·두통',
    usage: '성인 1~2정, 1일 3회 식후 복용',
    warningBeforeUse: '위장 질환·천식·아스피린 과민 환자는 복용 전 전문가와 상담하세요.',
    precautions: '소아·임산부·수유부는 의사·약사와 상담 후 복용하세요.',
    interactions: '항응고제, 메토트렉세이트 등과 상호작용이 있을 수 있습니다.',
    sideEffects: '위장 불편감, 어지러움, 피부 반응이 나타날 수 있습니다.',
    storage: '밀폐용기, 실온 보관',
    updatedAt: '20240101',
  },
  {
    itemName: '아스피린장용정100mg',
    entpName: '바이엘코리아',
    itemSeq: 'mock-aspirin-100',
    itemImage: '',
    efficacy: '해열, 진통, 항혈소판(의사 처방에 따른 심혈관 예방)',
    usage: '성인 1~2정, 1일 3~4회 식후 복용',
    warningBeforeUse: '15세 미만 바이러스성 질환 환자는 레이 증후군 위험이 있어 복용을 피하세요.',
    precautions: '위출혈·천식·NSAIDs 과민 환자는 주의하세요.',
    interactions: '항응고제, 다른 NSAIDs와 병용 시 출혈·위장 부작용 위험이 증가합니다.',
    sideEffects: '위장 출혈, 소화불량, 이명이 나타날 수 있습니다.',
    storage: '실온, 건소한 곳에 보관',
    updatedAt: '20240101',
  },
  {
    itemName: '부루펜시럽(이부프로펜)',
    entpName: '삼일제약',
    itemSeq: 'mock-burufen',
    itemImage: '',
    efficacy: '소아·성인 해열, 진통, 염증 완화',
    usage: '체중·연령에 따라 용량 조절, 식후 복용',
    warningBeforeUse: '천식·위궤양·신장·간 질환 환자는 복용 전 상담하세요.',
    precautions: '탈수 상태에서는 신장 부담이 커질 수 있어 수분 섭취를 유지하세요.',
    interactions: '이뇨제, ACE 억제제, 리튬 등과 상호작용이 있습니다.',
    sideEffects: '위장 불편, 발진, 부종이 나타날 수 있습니다.',
    storage: '냉장 보관(개봉 후 사용기한 준수)',
    updatedAt: '20240101',
  },
  {
    itemName: '판콜에이내복액',
    entpName: '동아제약',
    itemSeq: 'mock-pancol',
    itemImage: '',
    efficacy: '감기로 인한 발열, 오한, 두통, 콧물, 코막힘, 기침',
    usage: '성인 1회 1포, 1일 3회 식후 복용',
    warningBeforeUse: '고혈압·갑상선 질환·전립선 비대 환자는 복용 전 상담하세요.',
    precautions: '졸음을 유발할 수 있어 운전·기계 조작 시 주의하세요.',
    interactions: 'MAO 억제제, 항우울제 등과 병용 시 혈압 상승 위험이 있습니다.',
    sideEffects: '졸음, 구갈, 심박 증가, 소화불량이 나타날 수 있습니다.',
    storage: '실온 보관, 직사광선 피함',
    updatedAt: '20240101',
  },
  {
    itemName: '센트룸멀티비타민정',
    entpName: '헤일리온',
    itemSeq: 'mock-centrum',
    itemImage: '',
    efficacy: '비타민·미네랄 보충, 피로 회복 보조',
    usage: '성인 1정, 1일 1회 식후 복용',
    warningBeforeUse: '철분·칼슘 보충제와 동시 복용 시 흡수가 저해될 수 있습니다.',
    precautions: '권장량을 초과하지 마세요. 소아용이 아닙니다.',
    interactions: '테트라사이클린 등 일부 항생제와 간격을 두고 복용하세요.',
    sideEffects: '소화불량, 변색 소변 등이 나타날 수 있습니다.',
    storage: '실온, 습기 피해 보관',
    updatedAt: '20240101',
  },
  {
    itemName: '베아제정',
    entpName: '동아제약',
    itemSeq: 'mock-bease',
    itemImage: '',
    efficacy: '소화불량, 식욕부진, 과식에 따른 위장 불편',
    usage: '성인 1~2정, 1일 3회 식후 복용',
    warningBeforeUse: '췌장염·담석이 있는 경우 복용 전 상담하세요.',
    precautions: '장기간 고용량 복용은 피하세요.',
    interactions: '특별한 상호작용은 적으나 위산 억제제와 함께 복용 시 효과가 달라질 수 있습니다.',
    sideEffects: '드물게 복통, 설사가 나타날 수 있습니다.',
    storage: '실온 보관',
    updatedAt: '20240101',
  },
  {
    itemName: '마데카솔연고',
    entpName: '동국제약',
    itemSeq: 'mock-madecassol',
    itemImage: '',
    efficacy: '상처·화상·습진 등 피부 손상 부위의 보호·회복 보조',
    usage: '1일 1~3회 손상 부위에 얇게 도포',
    warningBeforeUse: '딥한 상처·감염 의심 부위에는 사용하지 마세요.',
    precautions: '눈·점막에 닿지 않게 하세요.',
    interactions: '다른 국소제와 병용 시 자극이 증가할 수 있습니다.',
    sideEffects: '국소 발진, 가려움이 나타날 수 있습니다.',
    storage: '실온, 직사광선 피함',
    updatedAt: '20240101',
  },
  {
    itemName: '알레그라정180mg',
    entpName: '사노피',
    itemSeq: 'mock-allegra',
    itemImage: '',
    efficacy: '알레르기성 비염, 두드러기에 따른 가려움·콧물·재채기',
    usage: '성인 및 12세 이상 1정, 1일 1~2회 복용',
    warningBeforeUse: '중증 신장 질환 환자는 용량 조절이 필요할 수 있습니다.',
    precautions: '졸음이 적은 항히스타민제이나 개인차가 있을 수 있습니다.',
    interactions: '알루미늄·마그네슘 함유 제산제와 함께 복용 시 흡수가 지연될 수 있습니다.',
    sideEffects: '두통, 오심, 피로감이 나타날 수 있습니다.',
    storage: '실온 보관',
    updatedAt: '20240101',
  },
  {
    itemName: '후시딘연고',
    entpName: '동화약품',
    itemSeq: 'mock-fucidin',
    itemImage: '',
    efficacy: '세균성 피부 감염(농가진, 상처 감염 등)',
    usage: '1일 2~3회 감염 부위에 도포',
    warningBeforeUse: '광범위·장기간 사용은 내성균 발생 위험이 있습니다.',
    precautions: '눈 주위·점막에는 사용하지 마세요.',
    interactions: '다른 국소 항생제와 무작위 병용은 피하세요.',
    sideEffects: '국소 자극, 가려움이 나타날 수 있습니다.',
    storage: '실온 보관',
    updatedAt: '20240101',
  },
  {
    itemName: '맥시부펜시럽',
    entpName: '한미약품',
    itemSeq: 'mock-maxibufen',
    itemImage: '',
    efficacy: '소아 해열, 진통',
    usage: '체중에 따라 용량 조절, 식후 복용',
    warningBeforeUse: '천식·위장 질환·탈수 시 복용 전 상담하세요.',
    precautions: '다른 해열·진통제와 중복 복용하지 마세요.',
    interactions: '이뇨제, 항응고제 등과 상호작용이 있을 수 있습니다.',
    sideEffects: '위장 불편, 발진이 나타날 수 있습니다.',
    storage: '냉장 보관(개봉 후 사용기한 준수)',
    updatedAt: '20240101',
  },
  {
    itemName: '우루사정100mg',
    entpName: '대웅제약',
    itemSeq: 'mock-ursa',
    itemImage: '',
    efficacy: '담즙 분비 촉진, 소화불량·간 기능 보조',
    usage: '성인 1~2정, 1일 2~3회 식후 복용',
    warningBeforeUse: '담관 폐쇄·급성 담낭염 환자는 복용을 피하세요.',
    precautions: '임산부·수유부는 의사와 상담 후 복용하세요.',
    interactions: '알루미늄 함유 제산제와 함께 복용 시 흡수가 저해될 수 있습니다.',
    sideEffects: '드물게 설사, 복통이 나타날 수 있습니다.',
    storage: '실온 보관',
    updatedAt: '20240101',
  },
  {
    itemName: '타치온정100mg',
    entpName: '일동제약',
    itemSeq: 'mock-tachion',
    itemImage: '',
    efficacy: '간 기능 보조, 항산화 보조',
    usage: '성인 1정, 1일 1~3회 식후 복용',
    warningBeforeUse: '천식 환자는 주의가 필요합니다.',
    precautions: '의사·약사 처방·지시에 따라 복용하세요.',
    interactions: '니트로글리세린 등과 병용 시 혈압 변화에 주의하세요.',
    sideEffects: '두통, 소화불량이 나타날 수 있습니다.',
    storage: '실온, 차광 보관',
    updatedAt: '20240101',
  },
];

export function browseMockMedicines(
  pageNo = 1,
  numOfRows = 25,
  itemName?: string,
): MedicineInfo[] {
  const pool = itemName?.trim()
    ? MOCK_MEDICINES.filter((item) =>
        item.itemName.toLowerCase().includes(itemName.trim().toLowerCase()),
      )
    : MOCK_MEDICINES;

  const start = (pageNo - 1) * numOfRows;
  return pool.slice(start, start + numOfRows);
}

export function searchMockMedicines(query: string, limit = 30): MedicineInfo[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  return MOCK_MEDICINES.filter(
    (item) =>
      item.itemName.toLowerCase().includes(q) ||
      item.entpName.toLowerCase().includes(q) ||
      item.efficacy.toLowerCase().includes(q),
  ).slice(0, limit);
}
