import type { GroupBuy } from '@/mockData/rewards/shop';

export const PARAMEDIC_GROUP_BUYS: GroupBuy[] = [
  {
    id: 'pgb1',
    itemName: '전문 구급대원 Trauma Bag (프로)',
    vendorName: 'EMS Pro Gear',
    originalPrice: 280_000,
    discountPrice: 198_000,
    depositPoints: 1_500,
    minThreshold: 25,
    currentOrders: 18,
    status: 'active',
    deadline: '2026-08-10',
  },
  {
    id: 'pgb2',
    itemName: '응급구조사 전용 플래시라이트 (1800lm)',
    vendorName: 'TacticalMed',
    originalPrice: 89_000,
    discountPrice: 62_000,
    depositPoints: 800,
    minThreshold: 40,
    currentOrders: 35,
    status: 'active',
    deadline: '2026-07-25',
  },
  {
    id: 'pgb3',
    itemName: 'EMS Trauma Shears + Holster 세트',
    vendorName: 'FieldReady',
    originalPrice: 45_000,
    discountPrice: 28_000,
    depositPoints: 400,
    minThreshold: 50,
    currentOrders: 42,
    status: 'active',
    deadline: '2026-07-30',
  },
  {
    id: 'pgb4',
    itemName: '응급구조사 전용 반사 피복 (4계절)',
    vendorName: 'SafeWear EMS',
    originalPrice: 165_000,
    discountPrice: 118_000,
    depositPoints: 1_200,
    minThreshold: 30,
    currentOrders: 30,
    status: 'completed',
    deadline: '2026-07-05',
  },
  {
    id: 'pgb5',
    itemName: '현장용 산소포화도 측정기 (공구)',
    vendorName: 'MedDevice Bulk',
    originalPrice: 320_000,
    discountPrice: 245_000,
    depositPoints: 2_000,
    minThreshold: 15,
    currentOrders: 9,
    status: 'verifying',
    deadline: '2026-08-20',
  },
];

export const PARAMEDIC_GROUP_BUY_ITEMS: Record<string, { emoji: string; specs: string }> = {
  pgb1: { emoji: '🎒', specs: '45L · 12포켓 · 방수 · 반사스트립' },
  pgb2: { emoji: '🔦', specs: '1800lm · USB-C · 8시간 · IP67' },
  pgb3: { emoji: '✂️', specs: '티타늄 · 홀스터 포함 · 현장 검증' },
  pgb4: { emoji: '🦺', specs: '4계절 · EN471 · 세탁 50회+' },
  pgb5: { emoji: '🫁', specs: 'SpO2 · PI · 알람 · 2년 보증' },
};
